version: '3.8'

# Services
services:

    # Nginx Service
    nginx:
        image: nginx:1.17
        ports:
          - 80:80
        volumes:
          - ./src:/var/www/app:ro
          - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
        depends_on:
          - php
    # PHP Service
    php:
        build: ./.docker/php_mysqli
        working_dir: /var/www/app
        volumes:
          - ./src:/var/www/app
        depends_on:
          - mysql

    # MySQL Service
    mysql:
        image: mysql:8
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: demo
        volumes:
          - ./.docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf:ro
          -  mysqldata:/var/lib/mysql

    # PhpMyAdmin Service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        ports:
          - 8080:80
        environment:
            PMA_HOST: mysql
        depends_on:
          - mysql

# Volumes
volumes:
  
    mysqldata: